CREATE DATABASE MATRICULA
USE MATRICULA

CREATE TABLE ALUMNO(
ID_ALUMNO INT AUTO_INCREMENT PRIMARY KEY,
DNI_ALUMNO CHAR(8) UNIQUE NOT NULL,
NOMBRES VARCHAR(50) NOT NULL,
APELLIDOS VARCHAR(50) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
EDAD INT NOT NULL,
GENERO CHAR(1) NOT NULL,
DIRECCION VARCHAR (100) NOT NULL,
CELULAR CHAR(9) NOT NULL,
CORREO VARCHAR(80) UNIQUE NOT NULL,
NOMBRE_APODERADO VARCHAR(50) NOT NULL,
CELULAR_APODERADO CHAR(9) NOT NULL,
USERNAME VARCHAR(50) UNIQUE NOT NULL,
PASSWORD_HASH VARCHAR(255) NOT NULL,
FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE AULA(
ID_AULA INT AUTO_INCREMENT PRIMARY KEY,
NIVEL VARCHAR(30)NOT NULL,
GRADO INT NOT NULL,
SECCION CHAR(1)NOT NULL,
VACANTES_TOTALES INT NOT NULL,
VACANTES_DISPONIBLES INT NOT NULL
);

CREATE TABLE RESERVA(
ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
ID_ALUMNO INT NOT NULL,
ID_AULA INT NOT NULL,
CODIGO_PAGO VARCHAR(20) UNIQUE NOT NULL,
FECHA_RESERVA DATETIME DEFAULT CURRENT_TIMESTAMP,
ESTADO_PAGO VARCHAR(20) DEFAULT 'PENDIENTE'
);

-- RELACIONES ENTRE TABLAS

ALTER TABLE reserva 
ADD CONSTRAINT FK_RELACION1
FOREIGN KEY (ID_ALUMNO) REFERENCES alumno (ID_ALUMNO);

ALTER TABLE reserva
ADD CONSTRAINT FK_RELACION2
FOREIGN KEY (ID_AULA) REFERENCES aula(ID_AULA);


INSERT INTO aula (nivel, grado, seccion, vacantes_totales, vacantes_disponibles)
VALUES
('Secundaria', 3, 'A', 30, 5),
('Secundaria', 3, 'B', 30, 0),
('Primaria', 1, 'A', 25, 25),
('Primaria', 6, 'B', 30, 12);

SELECT * FROM aula;