CREATE DATABASE MATRICULA
USE MATRICULA

CREATE TABLE ALUMNO(
ID_ALUMNO INT AUTO_INCREMENT PRIMARY KEY,
DNI_ALUMNO CHAR(8) UNIQUE NOT NULL,
NOMBRES VARCHAR(50) NOT NULL,
APELLIDOS VARCHAR(50) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
EDAD INT NOT NULL,
GENERO CHAR(1) NOT NULL,
DIRECCION VARCHAR(100) NOT NULL,
CELULAR CHAR(9) NOT NULL,
CORREO VARCHAR(80) UNIQUE NOT NULL,
NOMBRE_APODERADO VARCHAR(50) NOT NULL,
CELULAR_APODERADOR CHAR(9) NOT NULL,
USERNAME VARCHAR(50) UNIQUE NOT NULL,
PASSWORD_HASH VARCHAR(255) NOT NULL,
ESTADO VARCHAR(20) NOT NULL,
FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE AULA(
ID_AULA INT AUTO_INCREMENT PRIMARY KEY,
NIVEL VARCHAR(30) NOT NULL,
GRADO INT NOT NULL,
SECCION CHAR(1) NOT NULL,
VACANTES_TOTALES INT NOT NULL,
VACANTES_DISPONIBLES INT NOT NULL
);

CREATE TABLE RESERVA(
ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
ID_ALUMNO INT NOT NULL,
ID_AULA INT NOT NULL,
CODIGO_PAGO VARCHAR(20) UNIQUE NOT NULL,
FECHA_RESERVA DATETIME DEFAULT CURRENT_TIMESTAMP,
ESTADO_PAGO VARCHAR(20) DEFAULT 'PENDIENTE'
);

-- RELACIONES ENTRE TABLAS
ALTER TABLE RESERVA
ADD CONSTRAINT FK_RELACION1
FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO (ID_ALUMNO);  

ALTER TABLE RESERVA
ADD CONSTRAINT FK_RELACION2
FOREIGN KEY (ID_AULA) REFERENCES AULA(ID_AULA);



INSERT INTO AULA (nivel, grado, seccion, vacantes_totales, vacantes_disponibles) 
VALUES 
('Secundaria', 3, 'A', 30, 5),   
('Secundaria', 3, 'B', 30, 0),   
('Primaria', 1, 'A', 25, 25),    
('Primaria', 6, 'B', 30, 12);

SELECT * FROM aula;

CREATE TABLE USUARIO(
ID INT AUTO_INCREMENT PRIMARY KEY,
USERNAME VARCHAR(50) UNIQUE NOT NULL,
PASSWORD_HASH VARCHAR(200) NOT NULL,
ESTADO TINYINT(1) DEFAULT 1
);

INSERT INTO USUARIO (USERNAME, PASSWORD_HASH)
VALUES ('Admin','$2y$10$heuMG7aElXF5IiS4rCN49.T.smRQfhlCmVuoAh/SPpjQ6YA6qzZO6');

SELECT * FROM usuario


INSERT INTO ALUMNO (DNI_ALUMNO, NOMBRES, APELLIDOS, FECHA_NACIMIENTO, EDAD, 
GENERO, DIRECCION, CELULAR, CORREO, NOMBRE_APODERADO, 
CELULAR_APODERADOR, USERNAME, PASSWORD_HASH, ESTADO
)

VALUES (
'45789865','Pepito','Rosales','2004-05-15', 20, 
'M', 'Av. Perú','986532877','pepito@gmail.com', 'Sonia', 
'986532789', 'Pepito', 'mundo', 'A');

SELECT * FROM alumno

